2021-05-17 14:49:42,433 - gravity_core.wlogger - ERROR - Ошибка в работе оператора!
2021-05-17 14:49:42,436 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "wlauncher.py", line 59, in _start
    self.gravity_core.work()
  File "/home/qodex/Gravity_core_export/gravity_core/wengine.py", line 1181, in work
    self.operate_skud_stream()
  File "/home/qodex/Gravity_core_export/gravity_core/wengine.py", line 1124, in operate_skud_stream
    data = self.get_skud_data(self.sock)
  File "/home/qodex/Gravity_core_export/gravity_core/wengine.py", line 1145, in get_skud_data
    data = data.decode()
AttributeError: 'NoneType' object has no attribute 'decode'

